-- MySQL Script generated by MySQL Workbench
-- Fri Dec  1 20:35:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mysqlord
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mysqlord
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mysqlord` DEFAULT CHARACTER SET utf8 ;
USE `mysqlord` ;

-- -----------------------------------------------------
-- Table `mysqlord`.`tblItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mysqlord`.`tblItems` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_name` NVARCHAR(255) NULL,
  `item_type` NVARCHAR(255) NULL,
  `item_brand` NVARCHAR(255) NULL,
  `item_price` DOUBLE NULL,
  `item_ppath` NVARCHAR(255) NULL,
  `tblItemscol` VARCHAR(45) NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mysqlord`.`tblOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mysqlord`.`tblOrders` (
  `order_date` NVARCHAR(255) NULL,
  `order_time` NVARCHAR(255) NULL,
  `order_item` NVARCHAR(255) NULL,
  `order_type` NVARCHAR(255) NULL,
  `order_brand` NVARCHAR(255) NULL,
  `order_quantity` DOUBLE NULL,
  `order_tprice` DOUBLE NULL,
  `order_by` NVARCHAR(255) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
